version: "3.8"

services:
  myjenkins:
    container_name: my_custom_jenkins
    image: jenkins/jenkins:lts
    user: root
    environment:
      MY_NAME: "santi_devops"
      # Gmail extra configuration for mailer plugin
      JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
      SONARQUBE_HOST: mysonarqube
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Named  Docker volume details at the bottom
      - jenkins_home:/var/jenkins_home
      # WARNING:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net_devops
    deploy:
      resources:
        limits:
          memory: 1.5G
  mysonarqube:
    container_name: my_custom_sonarqube
    # build: ./sonarqube_home
    image: sonarqube:9.9-community
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_ES_JAVAOPTS: -Xms512m -Xmx512m -XX:+UseSerialGC
      SONAR_WEB_JAVAOPTS: -Xms512m -Xmx512m -XX:+UseSerialGC
    ports:
      - "9000:9000"
    networks:
      - net_devops
    volumes:
      - ./sonarqube_home/conf/:/opt/sonarqube/conf
      - ./sonarqube_home/data/:/opt/sonarqube/data
      - ./sonarqube_home/logs/:/opt/sonarqube/logs
      - ./sonarqube_home/extensions/:/opt/sonarqube/extensions
    deploy:
      resources:
         limits:
           memory:2G
    restart: unless-stopped
  mynexus:
    container_name: my_custom_nexus
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    networks:
      - net_devops
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5G
  

# To use docker-volume (custom_jenkins_home) instead of a directory path-file
volumes:
  jenkins_home:
    name: "custom_jenkins_home"
  nexus_data:
    name: "nexus_data"

networks:
  net_devops:
    driver: bridge
    name: net_devops
